config-version: 3

misc:
  kick: true
  version-check: true
  no-permission: "&cYou do not have permission to run this command."
  config-reloaded: "&aSuccessfully reloaded the config file"

click-swap-exploit:
  enabled: true
  kick-message: "§8[§dServerPatches§8] §fFailed packet filter - ClickSwapExploit"

bundle-select-exploit:
  enabled: true
  kick-message: "§8[§dServerPatches§8] §fFailed packet filter - BundleSelectExploit"

data-command-filter:
  enabled: true
  kick-message: "§8[§dServerPatches§8] §fFailed packet filter - DataCommandFilter"
