name: ServerPatches
api-version: 1.17
main: rs.jamie.serverpatches.ServerPatchesPlugin
version: '${version}'
authors: [Summiner]
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
commands:
  spatches:
    description: Adds the ability to reload ServerPatches config options, maybe more in the future
    usage: /spatches reload